#!/bin/bash

#SBATCH -J evolve_HPCTRNNs
#SBATCH -p general
#SBATCH -o filename_%j.txt
#SBATCH -e filename_%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=lstoltin@iu.edu
#SBATCH --nodes=5
#SBATCH --ntasks-per-node=1
#SBATCH --time=02:00:00
#SBATCH --mem=16G
#SBATCH -A general

#Load any modules that your program needs
module load python

#Run your program
srun /N/u/lstoltin/Carbonate/src/PyloricCTRNNHomeostasis/parallelevolution.py